- hosts: localhost
  tasks:
    # - name: 現在時刻
      # block: 
    - name: "コマンドを実行するタスク"
      command: "uptime"
      register: result
      failed_when: false # エラーメッセージを出力しない
      ignore_errors: true # エラーが発生しても無視する
    - name: "エラーメッセージをカスタマイズする"
      when: result.rc != 0
      fail: 
        msg: "{{ result }} 
        エラーメッセージをカスタマイズする"
    # - debug: 
        # msg: "{{ result }}"