- hosts: nodes
  become: yes
  vars:
    sample_vars: hogehoge
  tasks:
    - shell: uptime
      register: result
    - debug: 
        msg: "{{ result.stdout }}"
    - debug:
        msg: "{{ sample_vars }} "
    - shell: mkdir /var/log/adapter